/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ProyectoFinal;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class MostrarCurso extends javax.swing.JPanel {
    DefaultTableModel modeloCursos;
    /**
     * Creates new form MostrarCurso
     */
    public MostrarCurso() {
        String col[] = {"Nombre","Codigo","Descripcion","Profesor","Estudiantes"};
        
        modeloCursos = new DefaultTableModel(col, 0);
        for (int i = 0; i < Curso.listaDeCursos.size(); i++){
            String nombre = Curso.listaDeCursos.get(i).nombreCurso;
            String codigo = Curso.listaDeCursos.get(i).codigoCurso;
            String descripcion = Curso.listaDeCursos.get(i).descripcionCurso;
            String profesor = Curso.listaDeCursos.get(i).profesorAsignado;
            String estudiantes = Curso.listaDeCursos.get(i).estudiantesCurso.toString();
            Object[] data = {nombre, codigo, descripcion, profesor, estudiantes};
            modeloCursos.addRow(data);


        }
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(modeloCursos);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
